Q1. To check if there is any difference in the data type of variables list_ and array_list, and to print their data types:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. To print the data type of each and every element of both the variables list_ and array_list

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

for element in list_:
    print(f"Data type of element in list_: {type(element)}")

for element in array_list:
    print(f"Data type of element in array_list: {type(element)}")


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


Q3. After changing the data type of array_list to int, you can print the data types of each and every element in both variables

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

for element in list_:
    print(f"Data type of element in list_: {type(element)}")

for element in array_list:
    print(f"Data type of element in array_list: {type(element)}")


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>


Q4. To find the shape and size of the variable num_array:

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. To create a 3x3 numpy array containing zeros

In [5]:
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. To create a 5x5 identity matrix using numpy:

In [7]:
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
